### ISSUE TITLE
i18next 2.5.0+ requires initImmediate:false

### ISSUE THREAD

**Issue by nobeans** [sallar/i18next-sync-fs-backend#1]
Since i18next 2.5.0, `initImmediate:false` is required if you want to use i18next-sync-fs-backend.
Otherwise, `i18next#init()` returns immediately, regardless of whether a backend is sync or not.
I hope that this is written in README.

```
### 2.5.0
- allow null or empty string as defaultValue
- init option `initImmediate (default: true)` to init without immediate
```

https://github.com/i18next/i18next/blob/master/CHANGELOG.md#250

**Comment by arve0** [comment]
Thanks for reporting. I'll add a note in the readme.

**Comment by nobeans** [comment]
Thank you!
