### ISSUE TITLE
Supporting YAML

### ISSUE THREAD

**Issue by sallar** [sallar/i18next-sync-fs-backend#4]
Hi, 

Great repo! We're trying to use this in https://github.com/buttercup/buttercup, but we're going to support YAML instead of JSON. The official fs-backend from i18next guys supports YAML:
https://github.com/i18next/i18next-node-fs-backend/blob/master/src/index.js#L45

If you are willing to have YAML support as well, I can send a PR soon that makes it possible. What do you think? 

Thank you.

**Comment by arve0** [comment]
Hi!
It makes sense to support other formats, yes. I think a hook/preparse would make sense, so that the user can choose what extra to include. 

Like

'''
.use(Backend({
  parse: functionThatReturnsJSON
})
'''

**Comment by sallar** [comment]
@arve0 Thanks,

So you're suggesting passing in a parser function instead of adding the YAML into the plugin? (matching the file extension automatically, etc)

**Comment by arve0** [comment]
Yes, to avoid bloat for those not using YAML, JSON5 or NameYourFormat.

**Comment by sallar** [comment]
@arve0 Alright, valid point. I will send a PR with the parse function integration :) soon.

**Comment by sallar** [comment]
@arve0 Im not sure if I can add anything to this... everything's REALLY outdated... and the tests + testing system itself are failing

**Comment by sallar** [comment]
For now I made another fork to fix my problems: https://github.com/sallar/i18next-node-fs-sync-backend

**Comment by arve0** [comment]
Heh, yes this has not been updated in a while. https://github.com/i18next/i18next-node-fs-backend have diverged, an it seems like test are in a bad state (I did not look into them when I forked). 

Happy to merge your work or give up the npmjs name, to avoid unnecessary divergence/clutter in the package name space.

**Comment by sallar** [comment]
@arve0 Like I said, I'll be adding this to Buttercup and will maintain it at the same time too. I re-implemented the sync functionality based on a clean fork... and did some changes too. What is your preference? Do you think having PRs submitted to your repo is better or do you prefer that I will just take care of it myself?

**Comment by arve0** [comment]
> What is your preference?

I will always prefer maintaining less.

> Do you think having PRs submitted to your repo is better or do you prefer that I will just take care of it myself?

Transferring the repo to your name, and submit changes (in whatever workflow you use), will be the best. This ensures that those who use this plugin only need to bump version, and the plugin has a chronological timeline.

I've added you as a [contributor in npmjs](https://www.npmjs.com/package/i18next-sync-fs-backend). I tried transfering this repo to you, but you got a fork, so it failed.

**Comment by sallar** [comment]
Thanks @arve0, I will be happy to maintain this. I will try to delete that fork today and will report here. Transferring the repo to my name will ensure that links wont be broken (such as the one in i18next documentation) so thats a great idea.

**Comment by sallar** [comment]
@arve0 I have deleted my own fork. Can you try again please? Thanks a lot.

**Comment by sallar** [comment]
Thank you @arve0 :)
