### ISSUE TITLE
why reading files sync?

### ISSUE THREAD

**Issue by sibelius** [sallar/i18next-sync-fs-backend#7]
what are the benefits of reading files in sync await?

**Comment by sallar** [comment]
@sibelius I'm not sure I understand the question, could you please give a bit of context?

**Comment by sibelius** [comment]
this was forked from a async read of file right?

so why having a sync instead of async?

**Comment by sallar** [comment]
@sibelius Well, there are many situations that you can't wait on the i18n system to be ready or attach it to a callback, you want the languages files to be read and ready on startup and ready immediately, so you can use them in sync parts of the system. E.g: Immediately translate error messages or update system menus.

**Comment by sibelius** [comment]
tks for the explanation
